# Generated by Django 3.2.6 on 2023-07-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
