# Generated by Django 3.2.6 on 2023-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20230727_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_colaborador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
